development:
   adapter: postgresql
   encoding: unicode
   database: second-app_development
   pool:
   username: second-app

test:
   adapter: postgresql
   encoding: unicode
   database: second-app_development
   pool: 5
   username: second-app

production:
   adapter: postgresql
   encoding: unicode
   database: second-app_development
   pool: 5
   username: second-app

